/*
 * 
 * Copyright (C) 2007 Ken Ellinwood.
 * 
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 */
#ifndef __dump_h__
#define __dump_h__

/* Definitions generated by autotools. */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#include "jpmidi.h"

#ifdef __cplusplus
extern "C" {
#endif


void dump_init();
jpmidi_time_t* jpmidi_dump( jpmidi_time_t* from_time, uint32_t count, uint32_t flags);
void dump_event( jpmidi_time_t* time, jpmidi_event_t* event);
    
char* dump_get_program_description( uint8_t program);


    
#ifdef __cplusplus
}
#endif

#endif /* __dump_h__ */
    
